### ISSUE TITLE
Add support for wildcard artifacts

### ISSUE THREAD

**Issue by karelbemelmans** [Diogomrol/gocd-s3-artifact-plugin#10]
Using an artifact like *.tar.gz does not work as it does for the standard GoCD Artifact publishing (where all files matching the regex will get published).
Using a specific filename like templates.tar.gz does work.

**Comment by tomzo** [comment]
I am working on many improvements to this plugin with a goal to make it a substitute for the GoCD artifact store. I have already implemented pattern matching and directory upload and fetch #2.
WIP is in my fork - https://github.com/tomzo/gocd-s3-artifact-plugin/tree/dirfetch

**Comment by Diogomrol** [comment]
@tomzo feel free to open a PR here if you want me to add your changes to the Plugin and make a new version of it :)

**Comment by Diogomrol** [comment]
Close this as it was fixed by PR #11
