### ISSUE TITLE
Possibility of setting useful environment variables

### ISSUE THREAD

**Issue by arvindsv** [Diogomrol/gocd-s3-artifact-plugin#12]
Hello! This is more of an FYI. Sorry, I had to open it as an issue since I didn't know which forum to use.

It is now possible for this plugin endpoint to set environment variables to be used by the rest of the tasks in the job. See "Response body" in the documentation: https://plugin-api.gocd.org/current/artifacts/#fetch-artifact. I was thinking it could be done here: https://github.com/Diogomrol/gocd-s3-artifact-plugin/blob/2db42e0efb49dbbd7bdfc42d8a4a05a7de4474f6/src/main/java/diogomrol/gocd/s3/artifact/plugin/executors/FetchArtifactExecutor.java#L149
I thought I'd mention it since you have a section about environment variables in the README. Please close this "issue" once you've seen it. :)

/cc @Diogomrol @tomzo

**Comment by arvindsv** [comment]
Some more information:

https://github.com/gocd/gocd/pull/5188

https://github.com/gocd/docker-registry-artifact-plugin/pull/22

**Comment by tomzo** [comment]
@arvindsv thanks. I've seen this possibility already, but I don't see a use for it actually. We are simply fetching some files to a local directory. But then what would we export and why? Do you have some particular use case in mind?
I can see how it makes sense for the docker image plugin.

**Comment by tomzo** [comment]
Btw, the section about environment variables is about expanding them during artifact collection, not in the fetch.

**Comment by arvindsv** [comment]
@tomzo Yes, what you say makes sense. In this case, since it's a file, you probably don't have a need for adding extra information into the job's environment variables. I'll close this issue. Sorry! :/
