### ISSUE TITLE
Not able to fetch s3 directory in another pipeline . Also not showing me the subpath feature and i am using the latest release plugin.

### ISSUE THREAD

**Issue by phelepno** [Diogomrol/gocd-s3-artifact-plugin#14]
Able to publish data to s3 buckets .But in my scenario i have multiple projects using same s3 bucket and differentiate by s3 folders . But when my second pipeline trying to fetching out the data not able to fetch it bec data is present under folders.

Also , i am not able to see the subpath , directory feature in plugin .

**Comment by tomzo** [comment]
Hi @phelepno 

> Also , i am not able to see the subpath , directory feature in plugin .

Can you go to `http://<your-gocd-server>/go/admin/plugins` and check if the plugin version is actually `2.0.0` or `2.0.1`?

> But in my scenario i have multiple projects using same s3 bucket and differentiate by s3 folders . But when my second pipeline trying to fetching out the data not able to fetch it bec data is present under folders.

Sorry, but this too ambiguous. Can you provide more details on how you configured publish and fetch. It would be also useful if you posted the errors in the GoCD console and/or the logs.

**Comment by phelepno** [comment]
Version
1.0.0-12

Using this version.

**Comment by tomzo** [comment]
The subpath and directories support was added in `2.0.0` a few days ago. See the [changelog](https://github.com/Diogomrol/gocd-s3-artifact-plugin/blob/master/CHANGELOG.md#200-2019-may-19).
You can try it in https://github.com/Diogomrol/gocd-s3-artifact-plugin/releases/tag/2.0.1

But please note, that it is not compatible with previous version of the plugin - if you published some files with pre-2.0 then you may have trouble fetching them with 2.0.

**Comment by Diogomrol** [comment]
Closing this was the new version was already mentioned by @tomzo
