### ISSUE TITLE
Support IAM roles on EC2 instances

### ISSUE THREAD

**Issue by lobsterdore** [Diogomrol/gocd-s3-artifact-plugin#7]
When deploying GoCD to AWS it is best practice to use an IAM instance profile on the EC2 instance to provide AWS API access. It would be good if this plugin supported this method, possibly defaulting to an IAM profile if the key and secret are not specified.

**Comment by aarnone** [comment]
Somehow related: https://github.com/gocd/docker-registry-artifact-plugin/issues/30
